config/routes.rb
Rails.application.routes.draw do
  resources :blogs
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  validates :title, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:edit, :show, :update, :destroy]
  def index
    @blogs = Blog.all
  end

  def new
    @blog = Blog.new
  end

  def create
    @blog = Blog.new(blog_params)
    if @blog.save
      redirect_to blogs_path, notice: "作成しました"
    else
      render :new
    end
  end

  def edit
    # @blog = Blog.find(params[:id])
  end

  def show
    # @blog = Blog.find(params[:id])
  end

  def update
    # @blog = Blog.find(params[:id])
    if @blog.update(blog_params)
      redirect_to blogs_path, notice: "編集しました"
    else
      render :edit
    end
  end

  def destroy
    # @blog = Blog.find(params[:id])
    @blog.destroy
    redirect_to blogs_path, notice: "削除しました"
  end

  private
  def blog_params
    params.require(:blog).permit(:title, :content)
  end
  def set_blog
    @blog = Blog.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/blogs/_form.html.erb
<%= form_with(model: @blog, local: true) do |form| %>
  <% if @blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@blog.errors.count, "error") %> はこの投稿の保存を禁止しています:</h2>

      <ul>
      <% @blog.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="blot_title">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="blot_content">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>

  <%= form.submit %>
<% end %>

<%= link_to "一覧に戻る",blogs_path %>

app/views/blogs/edit.html.erb
<h1>Blogs#edit</h1>
<%= render 'form' %>

app/views/blogs/index.html.erb
<h1>Blogs#index</h1>
<p><%= notice %></p>
<table>
  <tr>
    <th>タイトル</th>
    <th>内容</th>
  </tr>
<% @blogs.each do |blog| %>
  <tr>
    <td><%= blog.title %></td>
    <td><%= blog.content %></td>
    <td><%= link_to "詳細確認", blog_path(blog.id) %></td>
    <td><%= link_to "編集確認", edit_blog_path(blog.id) %></td>
    <td><%= link_to "削除確認", blog_path(blog.id), method: :delete, data: { confirm: "本当によろしいでしょうか？"} %></td>
  </tr>
<% end %>
</table>
<%= link_to "新しく投稿する", new_blog_path %>

app/views/blogs/new.html.erb
<h1>Blogs#new</h1>
<%= render 'form' %>

app/views/blogs/show.html.erb
<h1>Blogs#show</h1>
<p>タイトル: <%= @blog.title %></p>
<p>内容: <%= @blog.content %></p>

<%= link_to "一覧に戻る", blogs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog01</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>